Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # ================================================= =
  # 1. SERVER NODE (Controller)
  # ================================================= =
  config.vm.define "ael-aminS" do |s|
    s.vm.hostname = "ael-aminS"
    s.vm.network "private_network", ip: "192.168.56.110"
    
    s.vm.provider "virtualbox" do |v|
      v.name = "ael-aminS"
      v.memory = 2048
      v.cpus = 2
    end

    s.vm.provision "shell", inline: <<-SHELL
      echo "Installing K3s Server..."
      # Install K3s and force it to use the specific eth1/enp0s8 IP for the cluster
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=enp0s8" sh -
      
      # Wait for token to be generated
      sleep 10
      
      # Copy the token to the shared /vagrant folder so the Worker can read it
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
      sudo chmod 644 /vagrant/node-token
    SHELL
  end

  # ================================================= =
  # 2. WORKER NODE (Agent)
  # ================================================= =
  config.vm.define "ael-aminSW" do |sw|
    sw.vm.hostname = "ael-aminSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
    
    sw.vm.provider "virtualbox" do |v|
      v.name = "ael-aminSW"
      v.memory = 1024
      v.cpus = 1
    end

    sw.vm.provision "shell", inline: <<-SHELL
      echo "Installing K3s Worker..."
      # Wait until the server has shared the token
      while [ ! -f /vagrant/node-token ]; do sleep 2; done
      
      TOKEN=$(cat /vagrant/node-token)
      SERVER_IP="192.168.56.110"
      
      # Install K3s Agent and connect to Server
      curl -sfL https://get.k3s.io | K3S_URL=https://${SERVER_IP}:6443 K3S_TOKEN=${TOKEN} INSTALL_K3S_EXEC="--node-ip=192.168.56.111 --flannel-iface=enp0s8" sh -
    SHELL
  end
end
